services:
  - type: web
    name: rag-policy-chatbot
    env: python
    region: oregon
    plan: free
    
    # 🔥 ONLY install dependencies, NO model loading!
    buildCommand: pip install --no-cache-dir -r requirements.txt
    
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 60 --worker-class sync --preload
    
    healthCheckPath: /health
    branch: main
    
    envVars:
      - key: GROQ_API_KEY
        sync: false
      
      - key: USE_GROQ
        value: true
      
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      
      # 🔥 Use same model at runtime (already embedded)
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      
      - key: CHUNK_SIZE
        value: 300
      
      - key: TOP_K
        value: 2
      
      - key: DEBUG
        value: False
      
      - key: PORT
        generateValue: true